"""Frozen physical + probabilistic evaluation metrics (evalphys v1.3.0)."""

from evalphys.calibration import (
    apply_strata,
    ence,
    gaussian_crps,
    gaussian_crps_torch,
    pit_histogram,
    spread_skill,
    summarize_calibration,
)
from evalphys.constants import DEPTH_BANDS, LC_LAT_RANGE, LC_LON_RANGE, N2_TOL, N2_TOL_SWEEP, STERIC_LC_RMS_CM, VERSION
from evalphys.gsw_backend import get_gsw
from evalphys.manifest import load_manifest, write_manifest
from evalphys.metrics import (
    drhodz_rmse,
    heave_vs_shape_split,
    isotherm_depth,
    isopycnal_ts,
    max_n2_depth,
    mixed_layer_depth,
    ocean_heat_content,
    sigma0_monotonicity_violations,
    spatial_sigma_consistency,
    static_stability_violations,
    steric_height_cm,
    steric_vs_adt,
    summarize_physical,
    to_teos10,
    ts_rmse_by_band,
    water_mass_rmse,
)

__all__ = [
    "DEPTH_BANDS",
    "LC_LAT_RANGE",
    "LC_LON_RANGE",
    "N2_TOL",
    "N2_TOL_SWEEP",
    "STERIC_LC_RMS_CM",
    "VERSION",
    "apply_strata",
    "drhodz_rmse",
    "ence",
    "gaussian_crps",
    "gaussian_crps_torch",
    "get_gsw",
    "heave_vs_shape_split",
    "isotherm_depth",
    "isopycnal_ts",
    "max_n2_depth",
    "load_manifest",
    "mixed_layer_depth",
    "ocean_heat_content",
    "pit_histogram",
    "sigma0_monotonicity_violations",
    "spatial_sigma_consistency",
    "spread_skill",
    "static_stability_violations",
    "steric_height_cm",
    "steric_vs_adt",
    "summarize_calibration",
    "summarize_physical",
    "to_teos10",
    "ts_rmse_by_band",
    "water_mass_rmse",
    "write_manifest",
]
